# Generated by Django 4.2.17 on 2024-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste', '0001_initial'),
        ('recycling_points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoint',
            name='accepted_categories',
            field=models.ManyToManyField(related_name='recycling_points', to='waste.wastecategory', verbose_name='accepted categories'),
        ),
    ]
