# Generated by Django 4.2.17 on 2024-12-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_points', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclingpoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='recyclingpoint',
            name='longitude',
        ),
    ]
