# Generated by Django 4.2.17 on 2024-12-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling_points', '0003_remove_recyclingpoint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='recyclingpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitude'),
        ),
    ]
