# Generated by Django 4.2.17 on 2024-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='A profile picture up to 5MB', null=True, upload_to='profile_pictures/'),
        ),
    ]
