# Generated by Django 4.2.17 on 2024-12-19 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('recycling_instructions', models.TextField(verbose_name='recycling instructions')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='waste_categories/icons/', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'waste category',
                'verbose_name_plural': 'waste categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('co2_saved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CO2 saved (kg)')),
                ('water_saved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='water saved (L)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_metrics', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('waste_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_metrics', to='waste.wastecategory', verbose_name='waste category')),
            ],
            options={
                'verbose_name': 'impact metric',
                'verbose_name_plural': 'impact metrics',
                'ordering': ['-date'],
            },
        ),
    ]
